### ISSUE TITLE
Failed to install the module with error msg: " package directory  does not exist"

### ISSUE THREAD

**Issue by rootchina** [vertica/Vertica-ML-Python#3]
### Anaconda Prompt
`(base) C:\Users\Jared\Documents\Visual_Studio_Code\Vertica\Vertica_ML_Python>python setup.py build`

C:\SW\Anaconda3\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running build
running build_py
error: package directory 'vertica_ml_python\vertica_ml_python' does not exist

**Comment by dflippo** [comment]
I can confirm that the same error also occurs using pip:
```
# pip3 install --upgrade git+git://github.com/vertica/Vertica-ML-Python.git
Collecting git+git://github.com/vertica/Vertica-ML-Python.git
  Cloning git://github.com/vertica/Vertica-ML-Python.git to /tmp/pip-req-build-fvn5_nus
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/vertica_ml_python.egg-info
    writing pip-egg-info/vertica_ml_python.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/vertica_ml_python.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/vertica_ml_python.egg-info/requires.txt
    writing top-level names to pip-egg-info/vertica_ml_python.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/vertica_ml_python.egg-info/SOURCES.txt'
    error: package directory 'vertica_ml_python/vertica_ml_python' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-fvn5_nus/
```
At my company we use docker to create our Jupyter notebook environments and fixing this issue would greatly simplify installation of the package.  I see the same error as roochina when I invoke the setup.py script directly.

**Comment by sitingren** [comment]
The quick workaround is deleting `package_dir={'':'vertica_ml_python'},` in setup.py file.
